package customer

import "time"

var TestCustomers = []Customer{
	{
		ID: 		  1,
		Name:          "Customer 1",
		Image:         "https://picsum.photos/200",
		Phone:         "01700000001",
		Username:      "customer1",
		Email:         "customer1@gmail.com",
		EmailVerified: true,
		PushToken:     "push_token",
		Password:      "password",
		IsActive:      true,
		Status:        "active",
		LastLogin:     time.Now(),
		Gender:        "male",
		DateOfBirth:   time.Now(),
	},
	{
		ID: 		  2,
		Name:          "Customer 2",
		Image:         "https://picsum.photos/200",
		Phone:         "01700000002",
		Username: 	"customer2",
		Email:         "customer2@email.com",
		EmailVerified: false,
		PushToken:     "push_token",
		Password:      "password",
		IsActive:      false,
		Status:        "inactive",
		LastLogin:     time.Now(),
	},
	{
		ID: 		  3,
		Name:          "Customer 3",
		Image:         "https://picsum.photos/200",
		Phone:         "01700000003",
		Username: 	"customer3",
		Email:         "customer3@email.com",
		EmailVerified: true,
		PushToken:     "push_token",
		Password:      "password",
		IsActive:      false,
		Status:        "blocked",
		LastLogin:     time.Now(),
	},
	{
		ID: 		  4,
		Name:          "Customer 4",
		Image:         "https://picsum.photos/200",
		Phone:         "01700000004",
		Username: 	"customer4",
		Email:         "customer4@email.com",
		EmailVerified: true,
		PushToken:     "push_token",
		Password:      "password",
		IsActive:      true,
		Status:        "active",
		LastLogin:     time.Now(),
	},
}

var TestCustomerAddresses = []CustomerAddress{
	{
		ID:         1,
		CustomerId: 1,
		Customer:  TestCustomers[0],
		Label:      "Home",
		Address:    "Address 1",
		Area:       "Area 1",
		PostalCode: "1000",
		Latitude:   23.777176,
		Longitude:  90.399452,
		Apartment:  "Apartment 1",
		Floor:      "Floor 1",
		RoadNo:     "Road No 1",
	},
	{
		ID:         2,
		CustomerId: 1,
		Customer:  TestCustomers[0],
		Label:      "Office",
		Address:    "Address 2",
		Area:       "Area 2",
		PostalCode: "1000",
		Latitude:   23.777176,
		Longitude:  90.399452,
		Apartment:  "Apartment 2",
		Floor:      "Floor 2",
		RoadNo:     "Road No 2",
	},
	{
		ID:         3,
		CustomerId: 2,
		Customer:  TestCustomers[1],
		Label:      "Office",
		Address:    "Address 2",
		Area:       "Area 2",
		PostalCode: "1000",
		Latitude:   23.777176,
		Longitude:  90.399452,
		Apartment:  "Apartment 2",
		Floor:      "Floor 2",
		RoadNo:     "Road No 2",
	},
	{
		ID:         4,
		CustomerId: 3,
		Customer:  TestCustomers[2],
		Label:      "Home",
		Address:    "Address 1",
		Area:       "Area 1",
		PostalCode: "1000",
		Latitude:   23.777176,
		Longitude:  90.399452,
		Apartment:  "Apartment 2",
		Floor:      "Floor 2",
		RoadNo:     "Road No 2",
	},
}